# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de5da96e716aec92f3daab518505787b7032586e3fd57f5eb68911dc6aca16b2749b28158be510c17782431064fdde5064dedf1af7cfb4076f8d76a3d02dfc6e

test:
  secret_key_base: 0df72b406542a2d29dbc94e8e337be060cbace358396be5e00bf37999926a7605e5b72e581328bdcc8d6ab90614effc10d69943014e0a607a8da5b9469398193

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
